# Product Extractor Recipe
# Extracts structured product data from retailer page content
#
# Used by WebAgent during research to extract products from
# retailer pages (search results, PDPs, category listings).

name: tools_product_extractor
category: tools
role: product_extractor
model_layer: MIND  # Extraction/reasoning tasks use MIND (temp 0.5)

# Prompt fragments (loaded in order)
prompt_fragments:
  - "apps/prompts/tools/product_extractor.md"

# Input documents
input_docs:
  - path: "extraction_goal"
    path_type: "runtime"
    optional: false
    max_tokens: 100
    description: "What to find (e.g., 'RTX 4060 gaming laptops under $1000')"

  - path: "page_url"
    path_type: "runtime"
    optional: false
    max_tokens: 200
    description: "URL of the page being extracted"

  - path: "page_content"
    path_type: "temp"
    optional: false
    max_tokens: 4000
    description: "Sanitized page text content for extraction"

  - path: "user_requirements"
    path_type: "runtime"
    optional: true
    max_tokens: 300
    description: "User requirements from query for relevance filtering"

# Output document
output_doc:
  path: "extracted_products.json"
  path_type: "temp"

# Token budget
token_budget:
  total: 6000
  prompt: 1200      # product_extractor.md prompt (includes examples)
  input_docs: 4600  # page content is the bulk
  output: 1500      # JSON products array
  buffer: 200

# Trimming strategy
trimming_strategy:
  method: intelligent_truncate
  priority:
    - keep: extraction_goal    # Always keep goal
    - keep: page_url           # Always keep URL
    - keep: user_requirements  # Always keep requirements
    - truncate: page_content   # Truncate page if too long

# Output schema
output_schema:
  type: object
  required:
    - products
    - page_type
    - total_found
    - extraction_method
  properties:
    products:
      type: array
      items:
        type: object
        required:
          - name
          - price
          - price_numeric
          - url
          - availability
          - vendor
          - confidence
        properties:
          name:
            type: string
          price:
            type: string
          price_numeric:
            type: number
          currency:
            type: string
          url:
            type: string
          image_url:
            type: string
          availability:
            type: string
            enum: ["in_stock", "out_of_stock", "limited", "preorder", "unknown"]
          vendor:
            type: string
          specs:
            type: object
          confidence:
            type: number
            minimum: 0
            maximum: 1
          extraction_notes:
            type: string
    page_type:
      type: string
      enum: ["search_results", "product_detail", "category_listing"]
    total_found:
      type: integer
    extraction_method:
      type: string
    warnings:
      type: array
      items:
        type: string

# Quality gates
quality_gates:
  schema_validation: true
  confidence_threshold: 0.5
  max_retries: 2

# Description
description: |
  Product Extractor extracts structured product data from retailer pages.

  **Extraction Rules:**
  - Parse current/sale prices, not original prices
  - Build complete URLs from relative paths
  - Extract specs from titles, tables, bullet points
  - Detect availability from stock indicators
  - Score confidence based on data completeness

  **Confidence Scoring:**
  - 0.90-1.0: All fields, clear formatting
  - 0.70-0.89: Most fields, minor ambiguity
  - 0.50-0.69: Key fields present, specs missing
  - 0.30-0.49: Basic fields only
  - < 0.30: Minimal data, high uncertainty

  **Page Types:**
  - search_results: Multiple product cards
  - product_detail: Single product with full specs
  - category_listing: Grid/list of products

  Input: extraction_goal + page_url + page_content + user_requirements
  Output: extracted_products.json with products array

# Integration
integration:
  invoked_by:
    - web_agent.extract_products
    - unified_web_extractor.extract
  invocation_point: after_page_load_during_research
