"""Core libraries for PandaAI v2."""

from libs.core.config import Settings, get_settings, load_model_registry
from libs.core.exceptions import (
    BudgetExceededError,
    CaptchaDetectedError,
    DocumentIOError,
    InterventionRequired,
    LLMError,
    PandaAIError,
    PhaseError,
    ResearchError,
    ToolError,
    ValidationError,
)
from libs.core.url_health import (
    URLHealthStatus,
    URLHealthReport,
    check_url_health,
    check_urls_in_text,
    get_unhealthy_urls,
)
from libs.core.models import (
    Claim,
    ContentReference,
    ContextSource,
    GatheredContext,
    Goal,
    GoalStatus,
    GoalValidation,
    Intent,
    InterventionRequest,
    InterventionSeverity,
    PlannerAction,
    PlannerRoute,
    QueryAnalysis,
    QueryType,
    ReflectionDecision,
    ReflectionResult,
    SynthesisResult,
    TaskPlan,
    ToolExecutionResult,
    ToolRequest,
    ToolResult,
    TurnMetadata,
    ValidationCheck,
    ValidationDecision,
    ValidationResult,
)

__all__ = [
    # Config
    "Settings",
    "get_settings",
    "load_model_registry",
    # URL Health
    "URLHealthStatus",
    "URLHealthReport",
    "check_url_health",
    "check_urls_in_text",
    "get_unhealthy_urls",
    # Exceptions
    "PandaAIError",
    "LLMError",
    "DocumentIOError",
    "PhaseError",
    "ToolError",
    "ValidationError",
    "InterventionRequired",
    "BudgetExceededError",
    "ResearchError",
    "CaptchaDetectedError",
    # Enums
    "QueryType",
    "Intent",
    "ReflectionDecision",
    "PlannerRoute",
    "PlannerAction",
    "ValidationDecision",
    "GoalStatus",
    "InterventionSeverity",
    # Models
    "ContentReference",
    "QueryAnalysis",
    "ReflectionResult",
    "ContextSource",
    "GatheredContext",
    "Goal",
    "ToolRequest",
    "TaskPlan",
    "ToolResult",
    "Claim",
    "ToolExecutionResult",
    "SynthesisResult",
    "ValidationCheck",
    "GoalValidation",
    "ValidationResult",
    "TurnMetadata",
    "InterventionRequest",
]
